# $Id: Makefile,v 1.1.1.1 2007/01/25 12:51:51 jiahao_jhou Exp $
# Makefile for the linux Sparc64-specific parts of the memory manager.
#

USE_STANDARD_AS_RULE := true
EXTRA_AFLAGS := -ansi

O_TARGET := mm.o
obj-y    := ultra.o fault.o init.o generic.o extable.o modutil.o

include $(TOPDIR)/Rules.make
